import fs from "fs-extra";
import path from "path";

/**
 * Next.js framework setup:
 * - Uses next/font/local (best practice for self-hosted fonts in Next.js 13+)
 * - Generates a fonts.js config that exports the font using next/font/local
 * - Generates a fonts.css fallback for older Next.js versions
 * - Instructions for integrating into layout.js / _app.js
 */
export async function writeNextjs({ fontData, outputPath, resolvedOutput, downloadedFiles }) {
  const familySlug = fontData.family.replace(/\s+/g, "-").toLowerCase();
  const familyCamel = toCamelCase(fontData.family);

  // 1. Write next/font/local config
  await writeFontConfig({ fontData, outputPath, resolvedOutput, downloadedFiles, familySlug, familyCamel });

  // 2. Write a fallback fonts.css (in case they're on pages router / older Next)
  await writeFallbackCSS({ fontData, resolvedOutput, downloadedFiles, familySlug });

  console.log(`\n  Next.js font setup complete.`);
  console.log(`\n  Using App Router (Next.js 13+)?`);
  console.log(`  Import your font config in app/layout.js:\n`);
  console.log(`    import { ${familyCamel} } from '${path.join(outputPath, "fontConfig.js")}';`);
  console.log(`    export default function RootLayout({ children }) {`);
  console.log(`      return (`);
  console.log(`        <html lang="en" className={${familyCamel}.variable}>`);
  console.log(`          <body>{children}</body>`);
  console.log(`        </html>`);
  console.log(`      );`);
  console.log(`    }\n`);
  console.log(`  Then use it in your CSS:`);
  console.log(`    body { font-family: var(--font-${familySlug}); }\n`);
  console.log(`  Using Pages Router?`);
  console.log(`  Import the fallback CSS in _app.js instead:`);
  console.log(`    import '${path.join(outputPath, "fonts.css")}';\n`);
}

async function writeFontConfig({ fontData, outputPath, resolvedOutput, downloadedFiles, familySlug, familyCamel }) {
  const srcEntries = downloadedFiles.map((file) => {
    return `    { path: './${file.fileName}', weight: '${file.weight}', style: 'normal' },`;
  });

  const lines = [
    `// Auto-generated by font-drop`,
    `// Font: ${fontData.family} | Source: ${fontData.source}`,
    `// Uses next/font/local for optimal performance (Next.js 13+)`,
    ``,
    `import localFont from 'next/font/local';`,
    ``,
    `export const ${familyCamel} = localFont({`,
    `  src: [`,
    ...srcEntries,
    `  ],`,
    `  variable: '--font-${familySlug}',`,
    `  display: 'swap',`,
    `});`,
  ];

  await fs.writeFile(path.join(resolvedOutput, "fontConfig.js"), lines.join("\n"), "utf8");
}

async function writeFallbackCSS({ fontData, resolvedOutput, downloadedFiles, familySlug }) {
  const cssLines = [];

  for (const file of downloadedFiles) {
    cssLines.push(`@font-face {`);
    cssLines.push(`  font-family: '${fontData.family}';`);
    cssLines.push(`  src: url('/${path.join("fonts", file.fileName)}') format('${file.format}');`);
    cssLines.push(`  font-weight: ${file.weight};`);
    cssLines.push(`  font-style: normal;`);
    cssLines.push(`  font-display: swap;`);
    cssLines.push(`}`);
    cssLines.push(``);
  }

  cssLines.push(`:root {`);
  cssLines.push(`  --font-${familySlug}: '${fontData.family}', sans-serif;`);
  cssLines.push(`}`);
  cssLines.push(``);
  cssLines.push(`.font-${familySlug} {`);
  cssLines.push(`  font-family: var(--font-${familySlug});`);
  cssLines.push(`}`);
  cssLines.push(``);

  for (const file of downloadedFiles) {
    cssLines.push(`.font-${familySlug}-${file.weight} {`);
    cssLines.push(`  font-family: var(--font-${familySlug});`);
    cssLines.push(`  font-weight: ${file.weight};`);
    cssLines.push(`}`);
    cssLines.push(``);
  }

  await fs.writeFile(path.join(resolvedOutput, "fonts.css"), cssLines.join("\n"), "utf8");
}

function toCamelCase(str) {
  return str
    .replace(/(?:^\w|[A-Z]|\b\w)/g, (word, index) =>
      index === 0 ? word.toLowerCase() : word.toUpperCase()
    )
    .replace(/\s+/g, "");
}
