import { toForwardSlash } from '../utils/index.js';
import fs from "fs-extra";
import path from "path";

/**
 * React framework setup:
 * - Generates @font-face declarations in fonts.css (or appends to existing)
 * - Optionally generates a fontHelper.js
 */
export async function writeReact({ fontData, outputPath, resolvedOutput, downloadedFiles, cssDestination, existingCssPath, generateHelper }) {
  const familySlug = fontData.family.replace(/\s+/g, "-").toLowerCase();

  // 1. Handle CSS based on user's choice
  if (cssDestination === "new") {
    await writeGlobalFontCSS({ fontData, resolvedOutput, downloadedFiles, familySlug });
    console.log(`\n  Import the stylesheet once in your entry file (main.jsx / index.jsx):`);
    console.log(`\n    import '${toForwardSlash(path.join(outputPath, "fonts.css"))}';`);
  } else if (cssDestination === "existing" && existingCssPath) {
    await appendToExistingCSS({ fontData, resolvedOutput, downloadedFiles, familySlug, existingCssPath, outputPath });
    console.log(`\n  Font styles appended to: ${chalk_path(existingCssPath)}`);
  } else {
    console.log(`\n  Skipped CSS setup — add your @font-face declarations manually.`);
  }

  // 2. Optionally write font helper
  if (generateHelper) {
    await writeFontHelper({ fontData, resolvedOutput, downloadedFiles, familySlug });
    console.log(`\n  Or use the font variables from the helper:`);
    console.log(`\n    import { fontFamily } from '${toForwardSlash(path.join(outputPath, "fontHelper.js"))}';`);
    console.log(`    <p style={{ fontFamily: fontFamily }}>Hello World</p>`);
  }

  console.log(`\n  Apply font classes directly:`);
  console.log(`\n    <p className="font-${familySlug}">Hello World</p>\n`);
}

async function writeGlobalFontCSS({ fontData, resolvedOutput, downloadedFiles, familySlug }) {
  const cssLines = generateFontCSS({ fontData, downloadedFiles, familySlug, urlPrefix: "./" });
  await fs.writeFile(path.join(resolvedOutput, "fonts.css"), cssLines, "utf8");
}

async function appendToExistingCSS({ fontData, resolvedOutput, downloadedFiles, familySlug, existingCssPath, outputPath }) {
  // Calculate relative path from the existing CSS file to the fonts folder
  const cssDir = path.dirname(existingCssPath);
  const relativePrefix = toForwardSlash(path.relative(cssDir, resolvedOutput)) + "/";

  const cssLines = generateFontCSS({ fontData, downloadedFiles, familySlug, urlPrefix: relativePrefix });
  const separator = `\n\n/* ── font-drop: ${fontData.family} ── */\n`;
  await fs.appendFile(existingCssPath, separator + cssLines, "utf8");
}

function generateFontCSS({ fontData, downloadedFiles, familySlug, urlPrefix }) {
  const lines = [];

  // @font-face
  for (const file of downloadedFiles) {
    lines.push(`@font-face {`);
    lines.push(`  font-family: '${fontData.family}';`);
    lines.push(`  src: url('${urlPrefix}${file.fileName}') format('${file.format}');`);
    lines.push(`  font-weight: ${file.weight};`);
    lines.push(`  font-style: normal;`);
    lines.push(`  font-display: swap;`);
    lines.push(`}`);
    lines.push(``);
  }

  // CSS variables
  lines.push(`:root {`);
  lines.push(`  --font-${familySlug}: '${fontData.family}', sans-serif;`);
  for (const file of downloadedFiles) {
    lines.push(`  --font-${familySlug}-${file.weight}: ${file.weight};`);
  }
  lines.push(`}`);
  lines.push(``);

  // Utility classes
  lines.push(`/* Utility classes */`);
  lines.push(``);
  lines.push(`.font-${familySlug} {`);
  lines.push(`  font-family: '${fontData.family}', sans-serif;`);
  lines.push(`}`);
  lines.push(``);

  for (const file of downloadedFiles) {
    lines.push(`.font-${familySlug}-${file.weight} {`);
    lines.push(`  font-family: '${fontData.family}', sans-serif;`);
    lines.push(`  font-weight: ${file.weight};`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join("\n");
}

async function writeFontHelper({ fontData, resolvedOutput, downloadedFiles, familySlug }) {
  const weights = downloadedFiles.map((f) => f.weight);

  const lines = [
    `// Auto-generated by font-drop`,
    `// Font: ${fontData.family} | Source: ${fontData.source}`,
    ``,
    `export const fontFamily = "'${fontData.family}', sans-serif";`,
    ``,
    `export const fontWeights = {`,
    ...weights.map((w) => `  "${w}": ${w},`),
    `};`,
    ``,
    `export const fontClasses = {`,
    `  base: "font-${familySlug}",`,
    ...weights.map((w) => `  "${w}": "font-${familySlug}-${w}",`),
    `};`,
  ];

  await fs.writeFile(path.join(resolvedOutput, "fontHelper.js"), lines.join("\n"), "utf8");
}

function chalk_path(p) {
  return p; // plain path for now, chalk not imported here
}





